#!/usr/bin/env python3

import argparse

from kdl_parser.urdf_parser_py.urdf import URDF

parser = argparse.ArgumentParser(usage='Load an URDF file')
parser.add_argument('file', type=argparse.FileType('r'), nargs='?',
                    default=None, help='File to load. Use - for stdin')
parser.add_argument('-o', '--output', type=argparse.FileType('w'),
                    default=None, help='Dump file to XML')
args = parser.parse_args()

if args.file is None:
    print('Please specify and URDF file to load!')
else:
    robot = URDF.from_xml_string(args.file.read())

print(robot)

if args.output is not None:
    args.output.write(robot.to_xml_string())
